language: swift
os: osx
osx_image: xcode10.2

script:
- xcodebuild clean build -project PSUIBarcodeScanner/PSUIBarcodeScanner.xcodeproj -scheme "PSUIBarcodeScanner" -sdk iphonesimulator

notifications:
  email: false

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME